# site properties and page defaults
title: MiM Lab
subtitle: MiM Lab @ PKU
description: Biomechanical imaging and modulation for living tissues  
header: images/nearwaves.png
footer: images/nearwaves.png
proofer: false

# site social media and other links
links:
  email: lgy@pku.edu.cn
  orcid: 0000-0002-5939-9293
  google-scholar: QtkQ_qQAAAAJ&hl
#  twitter: mingfaifong


### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
