- id: doi:10.1038/s41467-023-40625-y
  type: paper
  description: This article demonstrates the first ultrasonic shear wave imaging technique 
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-023-40625-y/MediaObjects/41467_2023_40625_Fig1_HTML.png?as=webp
  tags:
    - OCE
    - Ultra-wideband OCV
    - Ultrasonic shear waves
  buttons:
    - type: SI
      link: https://github.com/your-lab/some-repo
