- id: doi:10.1038/s41467-023-40625-y
  type: paper
  description: This article demonstrates the first ultrasonic shear wave imaging technique 
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-023-40625-y/MediaObjects/41467_2023_40625_Fig1_HTML.png?as=webp
  tags:
    - OCE
    - Ultra-wideband OCV
    - Ultrasonic shear waves
  buttons:
    - type: SI
      link: https://github.com/your-lab/some-repo
- id: doi:10.1126/sciadv.add4082
  type: paper
  description: This article proposes an acoustoelastic theory that lays the foundation for stress measurement without knowing constitutive parameters 
  image: https://www.science.org/cms/10.1126/sciadv.add4082/asset/ac99b6d1-858f-4d7e-a3af-2262df04d59b/assets/images/large/sciadv.add4082-f2.jpg
  tags:
    - USWE
    - Acoustoelasticity
    - Stress measurement
  buttons:
    - type: SI
      link: https://github.com/your-lab/some-repo    
