- id: doi:10.1038/s41467-023-40625-y
  type: paper
  description: This article demonstrates the first ultrasonic shear wave imaging technique 
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-023-40625-y/MediaObjects/41467_2023_40625_Fig3_HTML.png?as=webp
  tags:
    - Shear wave imaging
    - OCE
    - Ultra-wideband OCV
    - Ultrasonic shear wave
- id: doi:10.1126/sciadv.add4082
  type: paper
  description: This article proposes an acoustoelastic theory that lays the foundation for stress measurement without requiring knowledge of constitutive parameters
  image: https://www.science.org/cms/10.1126/sciadv.add4082/asset/ac99b6d1-858f-4d7e-a3af-2262df04d59b/assets/images/large/sciadv.add4082-f2.jpg
  tags:
    - Shear wave imaging
    - USWE
    - Acoustoelasticity
    - Stress measurement 
- id: doi:10.1109/TMI.2023.3338178
  type: paper
  description: This work establishes full-waveform inversion for near-field shear waves using deep learning, enabling super-resolution shear wave imaging 
  image: images/publications/TMI2024.png
  tags:
    - Shear wave imaging
    - PINN
    - FWI
    - Small tumor
- id: doi:10.1016/j.jmps.2022.105085
  type: paper
  description: In this work, we demonstrate that the supershear surface wave is consistently supported in solids, irrespective of the shear quality factor
  image: images/publications/JMPS2022.png
  tags:
    - Wave mechanics
    - Supershear
    - near-field surface wave
    - Anomalous acoustic effect
- id: doi:10.1109/TBME.2023.3338086
  type: paper
  description: In this work, we demonstrate the biomechanical heterogeneity of the cornea via high-resolution OCE, enabling early detection and staging of corneal diseases
  image: images/publications/TBME2024.png
  tags:
    - Shear wave imaging
    - OCE
    - Corneal biomechanics
    - In vivo measurements
- id: doi:10.1016/j.actbio.2023.12.019
  type: paper
  image: images/publications/AB2024.png
- id: doi:10.1038/s42005-022-01000-3
  type: paper
  image: images/publications/CP2022.png
- id: doi:10.1016/j.actbio.2022.04.030
  type: paper
  image: images/publications/AB2022.png
- id: doi:10.1109/TMI.2022.3141613
  type: paper
  image: images/publications/TMI2022.png
  description: In this work, we demonstrate the dynamic changes of arterial stiffness within cardiac cycles and find a scaling law between shear wave speed and local blood pressure
  image: images/publications/TBME2024.png
  tags:
    - Shear wave imaging
    - OCE
    - Corneal biomechanics
    - In vivo measurements  
- id: doi:10.1016/j.jbiomech.2021.110444
  type: paper
  image: images/publications/BM2021.png
- id: doi:10.1121/10.0002959
  type: paper
  image: images/publications/JASA2020.png
- id: doi:10.1016/j.jmps.2020.103896
  type: paper
  image: images/publications/JMPS2020.png
- id: doi:10.1016/j.eml.2020.100636
  type: paper
  image: images/publications/EML2020.png
